config/routes.rb
Rails.application.routes.draw do
	devise_for :users
	resources :lists
	root "static#home"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/list.rb
class List < ApplicationRecord
	belongs_to :user
	validates :item, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :lists
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  	protect_from_forgery with: :exception
	before_action :authenticate_user!
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
    @lists = current_user.lists
  end

  def show
    @list = current_user.lists.find(params[:id])
  end

  def new
    @list = current_user.lists.new
  end

  def create
    @list = current_user.lists.create(list_params)
    if @list.save
      redirect_to "/lists"
    else
      render :new
    end
  end

  def edit
    @list = current_user.lists.find(params[:id])
  end

  def update
    @list = current_user.lists.find(params[:id])
    if @list.update(list_params)
      redirect_to "/lists"
    else
      render :edit
    end
  end

  def destroy
    current_user.lists.destroy(params[:id])
    redirect_to "/lists"
  end

  protected
  def list_params
    params.require(:list).permit(:item)
  end
end

app/controllers/static_controller.rb
class StaticController < ApplicationController
	def home
		@lists = current_user.lists
		render template: "lists/index"
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TodoApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Caveat" rel="stylesheet">
  </head>

  <body>
  	<p class="navbar-text pull-right">
		<% if user_signed_in? %>
  			Logged in as <strong><%= current_user.email %></strong>.
  			<%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
  			<%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
		<% else %>
  			<%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
  			<%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
		<% end %>
	</p>

	<% if notice %>
    	<p class="alert alert-success"><%= notice %></p>
  	<% end %>

  	<% if alert %>
    	<p class="alert alert-danger"><%= alert %></p>
  	<% end %>

    <%= yield %>
  </body>
</html>

app/views/lists/_form.html.erb
<% if @list.errors.any? %>

<h3><%= pluralize(@list.errors.count, "error") %> prohibited this list item from being saved:</h3>

<ul>
  <% @list.errors.full_messages.each do |msg| %>
    <li> <%= msg %> </li>
  <% end %>
</ul>

<% end %>

<%= form_for(@list) do |f| %>

  <%= f.label :item %>
  <%= f.text_field :item %>

  <%= f.submit %>

<% end %>

app/views/lists/_list.html.erb
<div class="list">
  <p><%= list.item %></p>
  <%= link_to "Edit", edit_list_path(list) %> |
  <%= link_to "Delete", list, method: :delete, data: { confirm: "Are you sure?" } %>
  <br><br>
</div>

app/views/lists/edit.html.erb
<div class="logo">	
	<h1>Edit List Item</h1>
	<%= link_to "Back to List", lists_path %>
</div>
<%= render "form" %>

app/views/lists/index.html.erb
<div class="logo">	
	<h1>To Do List</h1>
</div>
<%= link_to "Add an Item", new_list_path %>
<br><br>
<%= render @lists %>

app/views/lists/new.html.erb
<div class="logo">	
	<h1>New List Item</h1>
	<%= link_to "Back to List", lists_path %>
</div>

<%= render 'form' %>

app/views/lists/show.html.erb
<div class="logo">
	<h1>Item Show Page</h1>
	<%= link_to "Back to List", lists_path %>
</div>

  <%= render @list %>